import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default ts.config(
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node,
				// Injected by vite.config.ts; declared for TypeScript in app.d.ts,
				// which ESLint does not read.
				__COMMIT__: 'readonly'
			}
		},
		rules: {
			// Storage throws in private browsing and there is nothing to do about
			// it — the empty catch is the handling.
			'no-empty': ['error', { allowEmptyCatch: true }],
			// Every link already goes through `base` from $app/paths, which is the
			// same thing resolve() does for the deployment prefix. Worth revisiting
			// if the typed-route half of resolve() becomes useful.
			'svelte/no-navigation-without-resolve': 'off',
			// `{' '}` is sometimes the only way to keep a space that Svelte would
			// otherwise collapse along with the newline beside it.
			'svelte/no-useless-mustaches': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Generated by `bun run portrait`; nothing here is hand-written.
		ignores: ['build/', '.svelte-kit/', 'src/lib/components/PixelPortrait.svelte']
	}
);
